---
- hosts: linux
  vars:
     training:  
        topic: ansible
        trainer: satish
        mode: online
        lab: AWS
  tasks:
  - name: print dict var
    debug:
      msg: "key is {{ item.key }} and value is {{ item.value }}"
    with_dict: "{{ training }}"

