---
- hosts: centos
  tasks:
  - name: Execute nested loop
    debug: msg=" ansible {{ item [0] }} on day {{ item [1] }} is {{ item [2] }} "
    with_nested:
    - [ 'tarining','lab','handson' ]
    - [ 1,2,3 ]
    - [ 'good','bad','great' ]
 
